name: backend_advanced_class CD

on:
  workflow_run:
    workflows: ["backend_advanced_class CI"]
    types:
      - completed
    branches: [ "main" ]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Connect & Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend_advanced:latest

            # 기존 컨테이너 중지 및 삭제
            if [ "$(docker ps -q -f name=backend_advanced)" ]; then
              docker stop backend_advanced
              docker rm backend_advanced
            fi

            # 새 컨테이너 실행
            docker run -d --name backend_advanced -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/backend_advanced:latest

            # 사용하지 않는 이미지 정리
            docker system prune -f
