name: backend_advancde_class CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스코드 체크아웃
      - name: Checkout
        uses: actions/checkout@v4

      # 2. JDK 17 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. gradlew 권한 부여 (Linux만 해당)
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean bootJar

      # 5. DockerHub 로그인
      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # 6. Docker 이미지 빌드 + 태깅
      - name: Build and Tag Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }} \
                       -t ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest .

      # 7. DockerHub에 Push
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myapp:latest